sabre-io/http

composer.json
lib/Client.php
lib/Request.php
lib/URLUtil.php
tests/HTTP/URLUtilTest.php

Requires https://github.com/fruux/sabre-uri/pull/1 to be merged.

Normalizing URI's before comparing them

---

lib/Sapi.php
tests/HTTP/SapiTest.php

I will reference this in another pullreq in sabre-dav shortly, explaining why I propose this change.

Don't send more data than what is promised in the HTTP content-length

---

lib/Message.php

Juste add a missing acceptable type for `setBody()`

correcting doc comments

---

lib/Auth/Bearer.php
tests/HTTP/Auth/BearerTest.php

Dependency of https://github.com/fruux/sabre-dav/issues/708

Add HTTP Bearer Auth support

---

lib/Auth/AWS.php
lib/Client.php
lib/Sapi.php
tests/HTTP/Auth/AWSTest.php
tests/HTTP/Auth/BasicTest.php
tests/HTTP/Auth/BearerTest.php
tests/HTTP/Auth/DigestTest.php
tests/HTTP/ClientTest.php

In this PR I fix some glitches I found. Some of them might be a matter of taste.

Fixing some tiny glitches

---

lib/Message.php
lib/MessageDecoratorTrait.php
lib/MessageInterface.php
lib/URLUtil.php
lib/Util.php
lib/functions.php

Fixes some typos, adds missing parameters

Fix documentation

---

composer.json

Which fixes the build because phpunit8 introduced bc breaking changes

Added a upper bound to version constraints

---

lib/Auth/Basic.php
lib/Auth/Bearer.php
lib/functions.php

This PR fixes the codestyle violations.

Fix codestyle

---

CHANGELOG.md
lib/Version.php

closes https://github.com/sabre-io/http/issues/122

Release 5.0.1

---

composer.json

added dev autloading for test classes
//cc @staabm

Added autoload for test classes

---

.gitignore
.php_cs.dist
.travis.yml
composer.json
lib/Client.php
lib/Message.php
lib/MessageDecoratorTrait.php
lib/MessageInterface.php
lib/ResponseDecorator.php
lib/functions.php
phpstan.neon
tests/phpunit.xml

Make the CI-related scripts here be similar to other `sabre-io`  repos.
Run `php-cs-fixer` in CI.

Update dependencies and tooling

---

CHANGELOG.md
lib/Version.php

I forgot to do this before making the release

changelog and VERSION bump for 5.1.2

---

tests/HTTP/SapiTest.php

cs-fixer now suggests some more PHP-doc format changes.

Apply cs-fixer changes

---

tests/HTTP/Auth/AWSTest.php
tests/HTTP/Auth/BasicTest.php
tests/HTTP/Auth/BearerTest.php
tests/HTTP/Auth/DigestTest.php
tests/HTTP/ClientTest.php
tests/HTTP/FunctionsTest.php
tests/HTTP/MessageDecoratorTest.php
tests/HTTP/MessageTest.php
tests/HTTP/NegotiateTest.php
tests/HTTP/RequestDecoratorTest.php
tests/HTTP/RequestTest.php
tests/HTTP/ResponseDecoratorTest.php
tests/HTTP/ResponseTest.php
tests/HTTP/SapiTest.php
tests/HTTP/URLUtilTest.php

See discussion in https://github.com/sabre-io/cache/pull/49

Call static assert functions with self::

---

CHANGELOG.md
lib/Sapi.php
lib/Version.php
tests/HTTP/Auth/AWSTest.php
tests/HTTP/FunctionsTest.php
tests/HTTP/SapiTest.php
tests/www/connection_aborted.php

see changelog for the PRs that I cherry-picked onto this branch, in preparation for making a 5.1.7 patch release.

Patches for 5.1.7

---

CHANGELOG.md
lib/Client.php
lib/Message.php
lib/Response.php
lib/Sapi.php
lib/Version.php
lib/functions.php
phpstan.neon
tests/HTTP/Auth/DigestTest.php
tests/HTTP/SapiTest.php
tests/www/connection_aborted.php

See changelog - this gets the code from #207 into the 6.0 branch, plus things that cs-fixer and phpstan insist on nowadays, and the changlog and version bump to 6.0.1 ready for a 6.0.1 release.

Patches for 6.0.1

---

CHANGELOG.md
lib/Version.php

- add changelogs from today's 5.1.7 and 6.0.1 releases
- add changelog for 7.0.1
- bump version to 7.0.1

Prepare 7.0.1

---

lib/Client.php
tests/HTTP/ClientTest.php

[6.0] Remove header overwrite with null

---

lib/Client.php
tests/HTTP/ClientTest.php

Back port #215 to the 5.1 branch

[5.1] Remove header overwrite with null

---

.github/workflows/ci.yml
composer.json
lib/Auth/AWS.php

to keep CI and dev dependencies up-to-date and passing.

Update CI stuff

---

.github/workflows/ci.yml
composer.json
lib/Auth/AWS.php

so that CI keeps passing in 6.0

Update CI stuff for 6.0

---

.github/workflows/ci.yml

so that CI keeps working for this branch

Update actions to current versions in 5.1 branch

---

composer.json
examples/stringify.php
tests/HTTP/ClientTest.php
tests/HTTP/MessageDecoratorTest.php

It wants to correct some code indent.

chore: adjust for php-cs-fixer 3.54.0

---

composer.json
examples/stringify.php
lib/Client.php
lib/Response.php
tests/HTTP/ClientTest.php
tests/HTTP/MessageDecoratorTest.php

php-cs-fixer has a few changes that it wants to apply.

chore: adjust for php-cs-fixer 3.54.0 (6.0 branch)

---

.github/workflows/ci.yml

to the current versions available.

chore: update GitHub workflow versions for 5.1 branch

---

.github/workflows/ci.yml
lib/Client.php
lib/Response.php

and adjust code for PHP 8.4 compliance.
Related issue https://github.com/sabre-io/event/issues/123

chore: add PHP 8.4 to CI of 5.1 branch

---

.github/workflows/ci.yml
.php-cs-fixer.dist.php
composer.json
lib/Client.php
lib/Response.php
phpstan.neon

And the minor code style changes that the latest php-cs-fixer wants.

add PHP 8.3 and 8.4 to CI of 6.0 branch
