sabre-io/http

lib/Auth/Basic.php
tests/HTTP/Auth/BasicTest.php

If the colon is missing (in `user:password`), `getCredentials` will return an array of one value instead of null whereas this is incorrect. We then check that the credentials form a pair of two values.

`getCredentials` returns null if incomplete

---

lib/Sapi.php

By closing the stream manually we make sure any streamwrapper for the stream has the chance to handle the fclose.

Close the body of a stream response after sending

---

CHANGELOG.md
lib/Message.php
lib/Version.php
tests/HTTP/MessageTest.php

`getBodyAsString` should only return at most as many bytes as the value of `Content-Length`, this allows users to pass much larger streams without having to copy and truncate them.

Respecting the Content-Length header when turning HTTP bodies into strings

---

examples/asyncclient.php
examples/basicauth.php
examples/client.php
examples/digestauth.php
examples/reverseproxy.php
lib/MessageDecoratorTrait.php
lib/Request.php
tests/HTTP/MessageDecoratorTest.php
tests/HTTP/SapiTest.php
tests/HTTP/URLUtilTest.php

`MessageDecoratorTrain::removeHeader()` should return bool as it's PHPDoc stats "This method should return true if the header was successfully deleted, and false if the header did not exist").
Currently this method doesn't return anything and this PR fixes the issue.

MessageDecorator: fix removeHeader() return value

---

lib/Message.php
lib/MessageDecoratorTrait.php
lib/MessageInterface.php
lib/Response.php
lib/ResponseInterface.php
lib/functions.php

Various typo fixes and PHPDoc improvements.
Also `DateTime` has a method `setTimezone()`, not `setTimeZone()`.

Various typo fixes and PHPDoc improvements

---

lib/Message.php
lib/MessageInterface.php
lib/Sapi.php
tests/HTTP/MessageTest.php
tests/HTTP/SapiTest.php

In `Sabre\HTTP\MessageInterface` (and `Sabre\HTTP\Message`), support `$body` to be a callback outputting the body into `php://output`
Some responses may be big, so it's not scalable to hold the whole response in a variable (in memory), see https://github.com/fruux/sabre-dav/pull/890.
`getBodyAsString()` and `getBodyAsStream()` doesn't currently work with the callback (throws an exception). It's implementation seem to be a bit complicated - mostly because we are able to produce output only once, but i'm open to ideas.
Snippet from `sabre/dav` to make `generateMultiStatus()` method work as a callback:
```php
function generateMultiStatus($fileProperties, $strip404s = false) {
$w = $this->xml->getWriter();
return function() use ($fileProperties, $strip404s, $w) {
$w->openUri('php://output'); …
```

Message: support body to be a callback 

---

CHANGELOG.md
lib/Request.php
lib/Sapi.php
tests/HTTP/Auth/AWSTest.php
tests/HTTP/Auth/BasicTest.php
tests/HTTP/Auth/BearerTest.php
tests/HTTP/Auth/DigestTest.php
tests/HTTP/MessageDecoratorTest.php
tests/HTTP/RequestDecoratorTest.php
tests/HTTP/RequestTest.php

This ensures that it's not possible to create a Request object that's
not valid.

The $uri and $method params are now required when setting up Request.

---

CHANGELOG.md
lib/Auth/Basic.php
tests/HTTP/Auth/BasicTest.php

Fixes #69. Thanks for the suggestion @rfc2822

Sending encoding="UTF-8" on basic auth challenges.

---

CHANGELOG.md
composer.json
lib/Message.php
lib/Version.php
tests/HTTP/MessageTest.php

Supporting empty Content-Length headers by ignoring them.

---

lib/Sapi.php

Replace stream_copy_to_stream with a chunked process, to handle file sizes hat do not fit into an integer.
Implementation according to http://php.net/manual/en/function.stream-copy-to-stream.php#98119, proposed and implemented by https://github.com/rikmeijer in https://github.com/nextcloud/server/issues/1707#issuecomment-291835214.

Work around file size issues at 32 Bit systems

---

.gitignore
README.md
lib/Message.php
lib/MessageDecoratorTrait.php
lib/MessageInterface.php
lib/Sapi.php
tests/HTTP/SapiTest.php

I added the binaries files, that will be installed once you install the dependencies, to the `gitignore` file.
fixes #81

support http2

---

lib/Sapi.php

Else the unit tests fail with php7

explicitly cast content length to int

---

tests/HTTP/RequestTest.php
tests/HTTP/ResponseTest.php

This fixes 3 failing tests on Windows (10).
Or should `$eol` be `\r\n`?

use the right line endings

---

lib/Client.php
tests/HTTP/ClientTest.php

As reported in issue #89 
See also [this related stack overflow article](https://stackoverflow.com/questions/9896727/how-to-reusing-a-curl-context-after-doing-a-put-request-in-php#15762515)

Executing multiple PUT requests makes curl emit warnings

---

README.md

We don't have a 5.0.0 branch, so didn't update build status.

README.md instructions should mention 5.0.0 instead of 3.0.0

---

composer.json
lib/Auth/AWS.php
lib/Auth/Digest.php
lib/Client.php
lib/Message.php
lib/MessageDecoratorTrait.php
lib/MessageInterface.php
lib/Request.php
lib/Response.php
lib/Sapi.php
lib/functions.php

Code optimization using PHPStorm plugin.
- improve performace
- minor fixes

Code optimization

---

lib/Auth/Digest.php

Without:
```
1) Sabre\HTTP\Auth\DigestTest::testInvalidDigest2
Trying to access array offset on value of type bool
/work/GIT/sabre-http/lib/Auth/Digest.php:124
/work/GIT/sabre-http/lib/Auth/Digest.php:94
/work/GIT/sabre-http/tests/HTTP/Auth/DigestTest.php:99
```
Also see https://github.com/sabre-io/dav/pull/1187

fix "Trying to access array offset on value of type bool" in 7.4

---

lib/Sapi.php
tests/HTTP/SapiTest.php

Issue #134 
The code was sending the fragment of data up to the next 4096-byte boundary, even if that exceeded the actual amount of content requested.

Fix short Content-Range download

---

lib/Sapi.php

`*` -> 0-n
`+` -> 1-n
Regex match would:
`Content-Range: bytes -/`
Beter use `+`

Improvement regex content-range

---

lib/Sapi.php
tests/HTTP/SapiTest.php

Fix for sending response of ranged streams when the content length provided is larger than the total number of bytes remaining in the stream.
In such cases the operation completes successfully but  the loop never exits as `stream_copy_to_stream() ` returns negative value.
This PR fixes this by checking the return value of `stream_copy_to_stream()` and returning when the return value is negative.

Fix Content is larger than the available bytes in the stream

---

.gitignore
.travis.yml
composer.json
tests/HTTP/Auth/AWSTest.php
tests/HTTP/Auth/DigestTest.php
tests/HTTP/MessageDecoratorTest.php
tests/HTTP/RequestDecoratorTest.php
tests/HTTP/RequestTest.php
tests/HTTP/ResponseDecoratorTest.php
tests/HTTP/ResponseTest.php

Updated from PHPUnit version 7 -> 8
Codebase changes were needed:
- Updated Composer PHPUnit version to ^8
- Refactored test to work with PHPUnit8
- Added PHPUnit Cache to gitignore
!important: PHPUnit8 requires PHP ^7.2 -> PHP version has to be updated bevor merging.
because of that not all checks are successfull.
//cc @staabm

Update to PHPUnit 8

---

.travis.yml
composer.json

to be consistent with the other repos.
It should be easy to keep supporting PHP 7.1 for a few more months.

Put back PHP 7.1 support

---

tests/HTTP/ClientTest.php

1) Change expected and actual to be around the usual way
2) Increase the limit of `memory_get_peak_usage()` from 40MB to 60MB. The actual value seems to now be around 49MB when running with PHPunit 9.4. Maybe PHPunit 9.1,2,3 or 4 did something that caused more memory to be used while running tests.
Fixes #157 
The other option is to remove this sort of run-time memory usage test. I guess there is some history for this, there must have been a bug where lots of memory got allocated/leaked...

Fix memory_get_peak_usage assert

---

.travis.yml
composer.json
lib/Auth/AbstractAuth.php
lib/Auth/Digest.php

1) sort out variables in `.travis.yml` for selecting to run php-cs-fixer, phpunit and phpstan
2) Add a matrix entry to run just phpunit on Ubuntu 20.04 "focal" with "nightly" PHP (which is the way to get PHP 8.0 at the moment)
3) When not running php-cs-fixer, explicitly remove it from `composer.json` (because php-cs-fixer does not yet support PHP 8.0, so composer cannot sort out dependencies if we have PHP 8.0 and php-cs-fixer 2.* together)
4) Fix the constructor declarations that have an optional parameter before a required parameter (PHP 8.0 complains about these)

Test with PHP 8.0

---

composer.json
lib/functions.php

The latest php-cs-fixer finds some new things. Code changes were needed in https://github.com/sabre-io/dav/pull/1316 for `sabre/dav`. We might as well consistently make sure to use at least this version 2.17.1 in all repos so that we are doing consistent code-style checking.
It complains about using `die()` rather than `exit()`

Use latest php-cs-fixer 2.17.1

---

lib/Message.php
lib/Response.php

Fixes following errors encounterd on a PHP 8.1 RC environment.
```
==> Error E_DEPRECATED in ... generated by file /var/glpi/vendor/sabre/http/lib/Message.php on line 91:
ctype_digit(): Argument of type null will be interpreted as string in the future
==> Error E_DEPRECATED in ... generated by file /var/glpi/vendor/sabre/http/lib/Response.php on line 152:
ctype_digit(): Argument of type int will be interpreted as string in the future
```

Fix deprecated usages on PHP 8.1

---

lib/Sapi.php

When looping over an array with foreach php will automatically convert
numeric values to integers. Since the key here is passed to substr it
has to be of string type. This commit explicitly convert the key value
to string.
I found this by accident by setting "env[LC_MESSAGES] = C.UTF-8" in my php-fpm pool configuration. For whatever reason this translated to '"6" => "C.UTF-8' in the $_SERVER array, which caused tons of headache while troubleshooting my nextcloud installation. I havn't really verified if this is the only bug of this kind (I fixed my problem by updating the php-configuration), but since I found this bug I thought I could at least report it.

Ensure $_SERVER keys are read as strings.

---

lib/Client.php
tests/HTTP/ClientTest.php

This is a rebased version of PR #172 (That PR comes from a `master` branch on the fork, so I can't easily push to update that)

Add resource size to CURL options in client

---

lib/functions.php
tests/HTTP/URLUtilTest.php

Use mb_check_encoding to detect encoding as mb_detect_encoding is misbehaving under PHP 8.1.
Also use mb_convert_encoding instead of utf8_encode as it’s getting deprecated in PHP 8.2.
Fixes https://github.com/sabre-io/http/issues/181

Fix encoding detection on PHP 8.1

---

.github/workflows/ci.yml

Various tests are typically skipped in CI because of unit test code like:
```
if (!function_exists('xdebug_get_headers')) {
$this->markTestSkipped('XDebug needs to be installed for this test to run');
}
```
```
PHPUnit 9.5.21 #StandWithUkraine
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
...............................................................  63 / 159 ( 39%)
............................................................... 126 / 159 ( 79%)
...SS.SSSSSSSSSSSSSSSSSSSS.......                               159 / 159 (100%)
Time: 00:00.423, Memory: 59.99 MB
OK, but incomplete, skipped, or risky tests!
Tests: 159, Assertions: 270, Skipped: 22.
Generating code coverage report in …
```

Install xdebug in CI so that all PHP unit tests run

---

lib/Sapi.php

Like described in https://github.com/sabre-io/http/issues/108 there are still issues, when 
- Nextcloud is running on 32 Bit-OS (like mine running on RPI)
- iOS-Clients want to access Movies
The workaround initially introduced with https://github.com/sabre-io/http/pull/74  is not necessary anymore. By the time the 64-Bit-Coding has been improved to serve 4MB chunks that don't hurt on 32Bit-systems.
There are similar recommendations (like https://help.nextcloud.com/t/ios-nextcloud-client-does-not-play-videos/99790/4 ) to step into the 64Bit-Coding _always_ by changing >4 to >0
This Pull-Request simply deletes the separation of 64/32 Bitsystems

Remove 4GB file size workaround for 32bit OS / Stream Videos on IOS

---

CHANGELOG.md
README.md
examples/asyncclient.php
lib/Auth/AbstractAuth.php
lib/Auth/Basic.php
lib/Auth/Bearer.php
lib/Auth/Digest.php
lib/Client.php
lib/Message.php
lib/MessageDecoratorTrait.php
lib/MessageInterface.php
lib/Request.php
lib/RequestDecorator.php
lib/RequestInterface.php
lib/Response.php
lib/ResponseDecorator.php
lib/ResponseInterface.php
lib/Sapi.php
lib/functions.php
tests/HTTP/Auth/BasicTest.php
tests/HTTP/Auth/BearerTest.php
tests/HTTP/NegotiateTest.php

I let the IDE tell me about this stuff.

Fix various small typos and grammar

---

tests/HTTP/ClientTest.php

See discussion https://github.com/sabre-io/dav/pull/1409#issuecomment-1185270940
The 'sabre/http' PHP unit tests are also run in the `sabre/dav` CI. The PHP environment is a bit "bigger" there, and `memory_get_peak_usage()` returns about 70MB, above the 60MB limit that the test allows.
This PR adds an env variable that can be defined to specify the peak memory usage that is allowed for the test. That will let us be more flexible in other CI.
I called it `SABRE_HTTP_TEST_GET_LARGE_CONTENT_MAX_PEAK_MEMORY_USAGE` - naming is hard, and I wanted a name that won't conflict with anything else in anyone's environment!

Allow testSendToGetLargeContent peak memory usage to be specified externally

---

CHANGELOG.md
lib/Version.php

Note: this release is primarily for PR #187 that adds flexibility to the unit test testSendToGetLargeContent so that it can be used more reliably in CI of `sabre/dav`
The changes to "real" code are mostly just typos and grammar that do not effect behavior.

changelog and VERSION bump for 5.1.6

---

tests/HTTP/Auth/AWSTest.php
tests/HTTP/FunctionsTest.php
tests/HTTP/SapiTest.php

This is a rebase of #98 
I rebased again today 2022-08-26, removed the small "real"  code change that was in `lib/functions.php` and squashed. Now this just has extra test cases, which looks fine. I will merge.

Test enhancement

---

lib/Auth/Digest.php
lib/Response.php
tests/HTTP/ResponseTest.php

1) `digestParts` should be a bit more flexible
2) Response.php `setStatus` - be more careful to set the variable to `int` - specially in the case when the passed-in value is `ctype_digit` (e.g. "200" "402" ...)
I tried phpstan level 7 and noticed these things that looked like they can and should be fixed/adjusted. Level 7 also reports a lot of stuff about PHP functions that can return "something or false" like `string|false` - there are quite a few places where the (remote) possibility of `false` is not checked. We put the return value straight into `string` (or whatever). In most of those cases, there is no good explanation for when `false` can happen - "the internet broke", "the operating system fell to pieces"... So I am not planning to analyze each one and work out some path to handle …

Adjust type declarations a little bit

---

CHANGELOG.md
README.md
examples/asyncclient.php
examples/client.php
lib/Auth/Basic.php
lib/Auth/Bearer.php
lib/Auth/Digest.php
lib/Client.php
lib/ClientHttpException.php
lib/HttpException.php
lib/Message.php
lib/MessageDecoratorTrait.php
lib/MessageInterface.php
lib/Request.php
lib/RequestDecorator.php
lib/RequestInterface.php
lib/ResponseInterface.php
lib/Sapi.php
lib/functions.php
tests/HTTP/ClientTest.php
tests/HTTP/URLUtilTest.php

No functional change. This just cleans up some crud in comments that my IDE keeps telling me about. May as well do it so I don't have to see it any more.

Cleanup grammar in comments

---

lib/Sapi.php
lib/functions.php
tests/HTTP/Auth/DigestTest.php

php-cs-fixer is reporting these. I guess there has been a newer php-cs-fixer version released that is different.
It wants "root" classes and functions to use the leading `\` - `\DateTime`.
We could change some php-cs-fixer rule settings, but actually it is easy to accept these code-style changes.

Adjust code style to meet current php-cs-fixer

---

lib/Sapi.php
tests/HTTP/SapiTest.php
tests/www/connection_aborted.php

https://github.com/sabre-io/http/pull/205 but with tests ;)
ignore_user_abort(true) instruct php to not abort the script on client disconnect. To avoid reading the entire stream and dismissing the data afterward, check between the chunks if the client is still there.

fix: handle client disconnect properly with ignore_user_abort true

---

README.md

and update table of major releases.
and update README with some grammar and punctuation suggested by my IDE.

[docs-only] Build status badge

---

CHANGELOG.md
lib/Version.php

This should not break any consumer. For anyone already using v7, it will report some types more accurately and so their consumer-code will be better analyzed by phpstan.
Note: most consumers will currently be using `sabre/http` along with `sabre/dav` and other sabre-io components. So the dependency requirements of the current `sabre/dav` 4.4.0 will pull in `sabre/http` 5.1.7 anyway. So there are probably not many projects using `sabre/http` major version 7 yet anyway.
Eventually I will work through the type-declarations and phpstan level 9 throughout the sabre-io repos - I have some work in `vobject` that I need to get back to, and then try the main `sabre/dav` repo. And then we can do a set of major releases of all that...

Prepare for release 7.0.2

---

lib/Client.php
tests/HTTP/ClientTest.php

This PR code prevents potential issues that could arise from setting CURLOPT_HTTPHEADER with an empty value. By adding a conditional check, we ensure that we only assign meaningful and valid header values.
```
$settings[CURLOPT_HTTPHEADER] = $nHeaders;
```
```
if (!empty($nHeaders)) {
$settings[CURLOPT_HTTPHEADER] = $nHeaders;
}
```
- Ensure that when $nHeaders contains valid header values, they are assigned to $settings[CURLOPT_HTTPHEADER].
- When $nHeaders is empty, $settings[CURLOPT_HTTPHEADER] should not be set or altered.

Improve CURLOPT_HTTPHEADER Setting Assignment

---

lib/Client.php
tests/HTTP/ClientTest.php

We don't have any tests related to HHVM. So remove the special checks from the test code, and remove comments about HHVM.

Remove HHVM special comments and test code

---

CHANGELOG.md
lib/Version.php

We need to release this test-only change, because the released code of major version 5 contains the tests as well as the code - a piece of history. And we want to keep doing that for compatibility.
`sabre/dav` also runs the `sabre/http` unit tests in its CI (another piece of history) and the HTTP test problem in issue #222 prevents unit tests from running properly to completion. For example:
https://github.com/sabre-io/dav/actions/runs/5889816355/job/15983958426?pr=1483
```
PHPUnit 9.6.10 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.33 with Xdebug 3.1.6
Configuration: tests/phpunit.xml
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"! …
```

[5.1] Prepare 5.1.9

---

tests/bootstrap.php

Fixes https://github.com/sabre-io/dav/issues/1484
When the sabre/http unit tests are run from inside the sabre/dav repo, the https://github.com/sabre-io/http/blob/master/tests/www/connection_aborted.php code includes https://github.com/sabre-io/http/blob/master/tests/bootstrap.php
https://github.com/sabre-io/http/blob/master/tests/bootstrap.php tries to find an `autoloader.php` to run, but in that environment, `autoloader.php` is actually found a few levels up - see the comments in the code for details.
This enhancement to https://github.com/sabre-io/http/blob/master/tests/bootstrap.php lets `connection_aborted.php` find `HTTP\Response()` and so it runs properly.
The test that makes use of it now passes even when run from inside the `sabre/dav` repo - I have tried manually on my laptop. …

[5.1] Enhance tests/bootstrap.php to find autoloader in more environments

---

composer.json
lib/Client.php
lib/Response.php

php-cs-fixer 3.49 (or some recent minor release) wants to use the `?` (nullable) syntax on optional parameters.
That syntax has been supported for quite a while since PHP https://www.php.net/manual/en/migration71.new-features.php
In the cases here, as well as the default value of the parameter being `null`, the `?` explicitly allows the caller to pass the value `null` if they want.
This seems reasonable, I don't see how it can break any existing usage.

chore: use php-cs-fixer 3.51

---

composer.json

We still support PHP 7.1 7.2 7.3 here, and that uses the old php-cs-fixer v2.
The new php-cs-fixer 3.64 wants to make changes to trailing-comma in `list()` - we want to avoid doing that in this old 5.1 branch, because php-cs-fixer v2 does not like it.

pin php-cs-fixer to 3.63.2 in 5.1 branch

---

.github/workflows/ci.yml
.php-cs-fixer.dist.php
composer.json
lib/Client.php
lib/Response.php
phpstan.neon

- apply php-cs-fixer 3.64 changes
- add PHP 8.4 to CI
- ignore phpstan reports about superfluous code - these are about code paths that phpstan knows are never taken. They do no harm. For now, I will ignore these phpstan reports, and leave the "protective but unnecessary" code
There are no more "Implicitly marking parameter $xxx as nullable is deprecated" code to be fixed.
The executable code changes in this PR are just what php-cs-fixer 3.64 wants to do.
I can make a new 7.0.4 release after this, that officially supports PHP 8.4

tool changes
